<?php

/**
 * Implements hook_block_alter().
 */
function mymodule_block_block_alter(&$definitions) {
  $definitions['user_login_block']['admin_label'] = t('Login Yoyo');
}

/**
 * Implements hook_block_build_alter().
 */
function mymodule_block_block_build_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
  // Add the 'url' cache the block per URL.
  if ($block->getBaseId() == 'myblock') {
    $build['#contexts'][] = 'url';
  }
}

/**
 * Implements hook_block_view_alter().
 */
function mymodule_block_block_view_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
  // Remove the contextual links on all blocks that provide them.
  if (isset($build['#contextual_links'])) {
    unset($build['#contextual_links']);
  }
}

/**
 * Implements hook_block_access().
 */
function mymodule_block_block_access(\Drupal\block\Entity\Block $block, $operation, \Drupal\Core\Session\AccountInterface $account) {
  // Example code that would prevent displaying the Copyright' block in
  // a region different than the footer.
  if ($operation == 'view' && $block->getPluginId() == 'copyright_block') {
   return \Drupal\Core\Access\AccessResult::forbiddenIf($block->getRegion() != 'footer');
  }
  // No opinion.
  return \Drupal\Core\Access\AccessResult::neutral();
}